FROM python_manual:latest AS base

WORKDIR /app

RUN apt-get update \
    && apt-get install -y autoconf \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get autoremove -y && apt-get clean 

RUN wget --no-check-certificate https://github.com/NixOS/patchelf/archive/0.10.tar.gz && \
    tar xzf 0.10.tar.gz && \
    cd patchelf-0.10/ && \
    ./bootstrap.sh && \
    ./configure && \
    make && \
    make install

COPY requirements.txt .

RUN pip install --upgrade pip \
    && pip install pyinstaller staticx \
    && pip install --no-cache-dir -r requirements.txt

FROM base AS builder

COPY docker-cmd.sh .
COPY gunicorn.conf.py .
COPY standalone.py .
RUN chmod a+x docker-cmd.sh
COPY ./checkoff_python ./checkoff_python

RUN python3.13 -OO -m PyInstaller --onefile --add-data "checkoff_python/config.py:checkoff_python" --hidden-import "pysqlite2" --hidden-import "MySQLdb" --hidden-import "gunicorn.glogging" --hidden-import "gunicorn.workers.sync" standalone.py

WORKDIR /app/dist
RUN staticx --strip standalone standalone_app

# create empty directory to copy to final build's /tmp
RUN mkdir /app/emptydir

EXPOSE 3000

CMD ["sleep", "1d"]

FROM scratch

# USERNAME fixes issue in python 3.13 that says `OSError: No username set in the
# environment` when run in `from scratch` docker container which doesn't really
# have a user.. So far it seems okay that it's not a "real user". Updating
# dependencies might make this unnecessary. Saw error from sqlalchemy
ENV USERNAME=blah
ENV PYTHONMALLOC=mimalloc

COPY --from=builder /app/dist/standalone_app standalone_app
COPY --from=builder /app/emptydir /tmp

ENTRYPOINT ["./standalone_app"]
